url: http://cargonauts.io

# Site settings
title: Cargonauts
tagline: The data center automation experts!
email: info@cargonauts.io 
description: "Cargonauts are experts in Datacenter Automation. We are experienced infrastructure engineers with a focus on containerization."

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: fed136
  secondary: fec503  
  secondary-dark: 333
  blue: 00b3fe

# Team names, titles and social links
people:
- name: Bas Tichelaar 
  pic: 1
  tagline: Entreprenerd
  social:
    - title: twitter
      url: https://twitter.com/bastichelaar
    - title: github
      url: http://github.com/bastichelaar
    - title: linkedin 
      url: http://nl.linkedin.com/in/bastichelaar 

- name: Simon van der Veldt 
  pic: 2
  tagline: Open Sourcerer
  social:
    - title: github
      url: http://github.com/simonvanderveldt
    - title: linkedin
      url: https://nl.linkedin.com/in/simonvanderveldt

- name: Ade Mochtar 
  pic: 3
  tagline: Cloud Engineer
  social:
    - title: github
      url: http://github.com/amochtar

- name: Richard Woudenberg 
  pic: 4 
  tagline: Troublemaker
  social:
    - title: github
      url: http://github.com/rchrd
    - title: linkedin
      url: https://nl.linkedin.com/in/richardwoudenberg

- name: Benny Cornelissen
  pic: 5
  tagline: Infrastructure Hacker
  social: 
    - title: twitter
      url: https://twitter.com/whieee
    - title: github
      url: http://github.com/bennycornelissen
    - title: bitbucket
      url: https://bitbucket.org/bcornelissen
    - title: linkedin
      url: https://nl.linkedin.com/in/bennycornelissen

- name: Armin Coralic 
  pic: 6 
  tagline: Dockerizer
  social:
    - title: github
      url: http://github.com/acoralic
    - title: linkedin
      url: https://nl.linkedin.com/in/armincoralic

- name: Roy Bos 
  pic: 7 
  tagline: Full Stack Developer 
  social:
    - title: github
      url: http://github.com/roybos
    - title: linkedin
      url: https://nl.linkedin.com/in/roybos

- name: Martin van Steenis 
  pic: 8
  tagline: Firestarter 
  social:
    - title: linkedin
      url: https://nl.linkedin.com/in/martinvansteenis

- name: Fai Fung
  pic: 9
  tagline: DevOps Advocate
  social:
    - title: twitter
      url: https://twitter.com/fai_fung
    - title: github
      url: https://github.com/ffung
    - title: linkedin
      url: https://nl.linkedin.com/in/faifung

- name: Sebastiaan van Steenis
  pic: 10
  tagline: Automation Geek
  social:
    - title: github
      url: https://github.com/superseb
    - title: linkedin
      url: https://nl.linkedin.com/in/sebastiaanvansteenis

- name: You?
  pic: 11
  url: https://xebia.com/careers/datacenter-automation-hero
  tagline: Data Center Automation Wizard
  social:
    - title: question-circle
      url: https://xebia.com/careers/datacenter-automation-hero

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/cargonauts
  - title: github
    url: http://github.com/cargonauts

# Postal address (add as many lines as necessary)
address:
  - line: Utrechtseweg 49
  - line: 1213 TL  
  - line: The Netherlands

# Build settings
markdown: kramdown
permalink: pretty
