url: https://nauts.io

# Site settings
title: Nauts
tagline: The data center automation experts!
email: info@nauts.io
description: "Nauts are experts in Datacenter Automation. We are experienced infrastructure engineers with a focus on containerization."

# Build settings
markdown: kramdown
kramdown:
    input: GFM
permalink: pretty

gems:
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-paginate

paginate: 3
paginate_path: "/page/:num/"

#Disqus shortname
disqus: nautsio
#Enable when running locally
disqus_developer: 1
