url: http://cargonauts.io

# Site settings
title: Cargonauts
tagline: The data center automation experts!
email: info@cargonauts.io 
description: "Cargonauts are experts in Datacenter Automation. We are experienced infrastructure engineers with a focus on containerization."

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: fed136
  secondary: fec503  
  secondary-dark: 333
  blue: 00b3fe

collections:
  - team
  - events
  - expertise

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/cargonauts
  - title: github
    url: http://github.com/cargonauts

# Postal address (add as many lines as necessary)
address:
  - line: Utrechtseweg 49
  - line: 1213 TL  
  - line: The Netherlands

# Build settings
markdown: kramdown
permalink: pretty
gems:
  - jekyll-redirect-from
